From broken to slightly less broken?
Trying to fix broken logon w/current gmusicapi. (Orig script written for pre-5.0 release?)

-------------------

Before:

Traceback (most recent call last):
  File "runme.py", line 9, in <module>
    ms = MusicSync("me@gmail.af","MyPass")
  File "/root/Rhapsody-to-Google-Music-master/musicsync.py", line 87, in __init__
    self.logged_in = self.auth()
  File "/root/Rhapsody-to-Google-Music-master/musicsync.py", line 97, in auth
    self.logged_in = self.mc.login(self.email, self.password)
TypeError: login() takes exactly 4 arguments (3 given)

---------

After:   

Still fails for me, but only because I'm testing on a VPS with 00-00-00* as a MAC. 

  File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 57, in login
    raise OSError("a valid MAC could not be determined."
OSError: a valid MAC could not be determined. Provide an android_id (and be sure to provide the same one on future runs).

Need more to pass an alt android_id - Entered a fake/random one, and it got further (oauth challenge) but still failed.